services:

  backend:
    build:
      context: ./server
    environment:
      - PORT=8000
      - NODE_ENV=production
    env_file:
      - ./server/.env
    networks:
      - app-network
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./client
    environment:
      - SERVER_URL=http://backend:8000
      - FRONTEND_URL=http://frontend:3000
      - NEXTAUTH_URL=https://www.linguardian.com
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=production
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env.local
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
      
