services:

  backend:
    build:
      context: ./server
    environment:
      - PORT=8000
      - NODE_ENV=production
    env_file:
      - ./server/.env
    networks:
      - app-network
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./client
    environment:
      - SERVER_URL=http://backend:8000
      - FRONTEND_URL=http://frontend
      - NEXTAUTH_URL=http://localhost
      - NODE_ENV=production
    env_file:
      - ./client/.env.local
    ports:
      - "80:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
      
