services:

  backend:
    build:
      context: ./server
    environment:
      - PORT=8000
      - NODE_ENV=production
      - MONGO_URL=${MONGO_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    networks:
      - app-network
    ports:
      - "8000:8000"
    image: backend:latest

  frontend:
    build:
      context: ./client
    image: frontend:latest
    args:
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    environment:
      - NODE_ENV=production
      - SERVER_URL=http://backend:8000
      - FRONTEND_URL=http://frontend:3000
      - NEXTAUTH_URL=https://www.linguardian.com
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_ID=${GOOGLE_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge