services:

  backend:
    image: ${AWS_ID}.dkr.rcr.${AWS_REGION}.amazonaws.com/linguardian:backend-latest
    environment:
      - PORT=8000
      - NODE_ENV=production
      - MONGO_URL=${MONGO_URL}
    networks:
      - app-network
    ports:
      - "8000:8000"

  frontend:
    image: ${AWS_ID}.dkr.rcr.${AWS_REGION}.amazonaws.com/linguardian:frontend-latest
    environment:
      - NODE_ENV=production
      - SERVER_URL=http://backend:8000
      - FRONTEND_URL=http://frontend:3000
      - NEXTAUTH_URL=https://www.linguardian.com
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge